module ReadCoverageDistributions
#njdkd vd c 

include("HistogramReadCoverages.jl")
include("OceanIslandsDistributions.jl")

export simulate_and_get_coveage_hist_2,simulate_oceansislands,plot_oceansislands_simulation,no_islands_vs_no_reads_simulation,no_oceans_vs_no_reads_simulation,avg_length_oceans_vs_no_reads_simulation,avg_length_islands_vs_no_reads_simulation,simulate_and_get_coveage_hist_3,no_reads_vs_no_islands,simulate_readcoverage,Para,increment!,hist_add!,vec_hist_add!,simulate_and_get_coveage_hist,plot_readcoverage_simulation


end
